### PR TITLE
fix: Fix republishing volumes after a Node restart

### LINKED ISSUE #262: Pods with listener volumes can not be restarted after their node is restarted
### Affected Stackable version

nightly (but it's an old issue)

### Current and expected behavior

Repro:

1. Install SDP
2. Create a pod that mounts a list-op volume (such as `examples/`)
3. Wait for it to start up
4. Restart the node that the pod is running on (k3d note: run `docker kill k3d-node-name && docker restart k3d-node-name`, a plain `docker restart k3d-node-name` will delete all pods on the node first, bypassing the issue. other distributions may do similar things)

Expected:
The pod is eventually restarted and comes back online once the node is running again.

Current behaviour:
The pod gets stuck as unknown. If `kubectl describe`d, a bunch of error messages about failed file writes have been written as Events:

> MountVolume.SetUp failed for volume "pvc-438df3de-141b-4dbe-a97f-065ba704c3b2" : rpc error: code = Internal desc = failed to prepare pod dir at "/var/lib/kubelet/pods/5784b379-b5cb-4d80-9bf5-64f40bb551ca/volumes/kubernetes.io~csi/pvc-438df3de-141b-4dbe-a97f-065ba704c3b2/mount": failed to write content: File exists (os error 17)

### Possible solution

Workaround: Deleting the pod should let it be recreated with a new ID, which _is_ able to start without conflicts.

1. Allow overwriting volume files (currently this is disallowed as a safeguard, but that could be disabled)
2. Mount volumes as a tmpfs (like secret-operator currently does, but this requires the operator to always run with root privileges)

### Additional context

_No response_

### Environment

Client Version: v1.30.2
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.31.0+k3s1

### Would you like to work on fixing this bug?

yes

### PR DESCRIPTION
**Pull request by siegfriedweber**
# Description

Fix the error "failed to write content: File exists (os error 17)" after a Node restart.

Fixes #262 

## Definition of Done Checklist

- Not all of these items are applicable to all PRs, the author should update this template to only leave the boxes in that are relevant
- Please make sure all these things are done and tick the boxes

```[tasklist]
# Author
- [x] Changes are OpenShift compatible
- [x] Helm chart can be installed and deployed operator works
- [x] Integration tests passed (for non trivial changes)
- [x] Changes need to be "offline" compatible
```

```[tasklist]
# Reviewer
- [ ] Code contains useful comments
- [ ] Code contains useful logging statements
- [ ] (Integration-)Test cases added
- [ ] Documentation added or updated. Follows the [style guide](https://docs.stackable.tech/home/nightly/contributor/docs/style-guide).
- [ ] Changelog updated
- [ ] Cargo.toml only contains references to git tags (not specific commits or branches)
```

```[tasklist]
# Acceptance
- [ ] Feature Tracker has been updated
- [ ] Proper release label has been added
- [ ] [Roadmap](https://github.com/orgs/stackabletech/projects/25/views/1) has been updated
```

### CODE REVIEW

File: rust/operator-binary/src/csi_server/node.rs [hunk 1]
```diff
@@ -591,12 +591,18 @@ mod pod_dir {
             }
             default_addr_dir.get_or_insert(addr_dir);
         }
+
+        let default_addr_link = target_path.join("default-address");
+        // Remove any existing symlink because `tokio::fs::symlink` fails if it already exists.
+        // This happens if the node was restarted. The pod then restarts with the same UID and
+        // the pre-populated volume.
+        let _ = tokio::fs::remove_file(&default_addr_link).await;
```
[the remark this answers is not in the document]
Comment (siegfriedweber) [reply rust/operator-binary/src/csi_server/node.rs]: Implemented in 3dc5186186dd0ce7393bd14f10fb6caea23c0057

File: rust/operator-binary/src/csi_server/node.rs [hunk 2]
```diff
@@ -591,14 +591,26 @@ mod pod_dir {
...
+            .strip_prefix(target_path)
+            .context(DefaultAddrIsOutsideRootSnafu)?
+            .to_owned();
+        let default_addr_dir_link = target_path.join("default-address");
+        // Check if the symlink needs to be updated
+        if tokio::fs::read_link(&default_addr_dir_link)
+            .await
+            .ok()
+            .as_ref()
+            != Some(&relative_default_addr_dir)
```
Comment (nightkr) [inline rust/operator-binary/src/csi_server/node.rs:606]: Nit:

```suggestion
            .as_ref()
            != Ok(&relative_default_addr_dir)
```

**Review by nightkr — APPROVED** [review]

File: rust/operator-binary/src/csi_server/node.rs (hunk 2 above)
Comment (nightkr) [reply rust/operator-binary/src/csi_server/node.rs:606]: Ah, right, nevermind; `std::io::Error` ain't `PartialEq`.

**Comment by lfrancke** [comment]
Can you please add a release note snippet in the form "Previously, <this went wrong>. With this release, <this was fixed in the following way>."

**Comment by siegfriedweber** [comment]
> Can you please add a release note snippet in the form "Previously, 'this went wrong'. With this release, 'this was fixed in the following way'."

Already done in #262, see https://docs.stackable.tech/home/stable/release-notes/#_bug_fixes.
